#!/usr/bin/env fish

# Usage:
#
# To enable fish <tab> completion for justrun, add the following line to
# your ~/.config/fish/config.fish file:
#
# justrun --completion=fish | source

complete -c justrun -a "(justrun --tasks-simple)" -f
