#!/usr/bin/env fish

# Usage:
#
# To enable fish <tab> completion for jsrun, add the following line to
# your ~/.config/fish/config.fish file:
#
# jsrun --completion=fish | source

complete -c jsrun -a "(jsrun --tasks-simple)" -f
